<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20241219072956 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE duree_session (gender_id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, duree INT NOT NULL, PRIMARY KEY(gender_id))');
        $this->addSql('CREATE TABLE gender (gender_id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(50) NOT NULL, PRIMARY KEY(gender_id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_C7470A425E237E06 ON gender (name)');
        $this->addSql('CREATE TABLE generate_pin (generate_pin_id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, date_debut_id TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, date_fin_id TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, pin VARCHAR(100) NOT NULL, user_id INT NOT NULL, PRIMARY KEY(generate_pin_id))');
        $this->addSql('CREATE INDEX IDX_43904F9A76ED395 ON generate_pin (user_id)');
        $this->addSql('CREATE TABLE limite_tentative_session (gender_id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, limite INT NOT NULL, PRIMARY KEY(gender_id))');
        $this->addSql('CREATE TABLE role (role_id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(50) NOT NULL, PRIMARY KEY(role_id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_57698A6A5E237E06 ON role (name)');
        $this->addSql('CREATE TABLE users (user_id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, username VARCHAR(50) NOT NULL, password VARCHAR(50) NOT NULL, email VARCHAR(50) NOT NULL, birth_date DATE NOT NULL, token VARCHAR(50) DEFAULT NULL, gender_id INT NOT NULL, role_id INT NOT NULL, PRIMARY KEY(user_id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_1483A5E9F85E0677 ON users (username)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_1483A5E9E7927C74 ON users (email)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_1483A5E95F37A13B ON users (token)');
        $this->addSql('CREATE INDEX IDX_1483A5E9708A0E0 ON users (gender_id)');
        $this->addSql('CREATE INDEX IDX_1483A5E9D60322AC ON users (role_id)');
        $this->addSql('ALTER TABLE generate_pin ADD CONSTRAINT FK_43904F9A76ED395 FOREIGN KEY (user_id) REFERENCES users (user_id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE users ADD CONSTRAINT FK_1483A5E9708A0E0 FOREIGN KEY (gender_id) REFERENCES gender (gender_id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE users ADD CONSTRAINT FK_1483A5E9D60322AC FOREIGN KEY (role_id) REFERENCES role (role_id) NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE generate_pin DROP CONSTRAINT FK_43904F9A76ED395');
        $this->addSql('ALTER TABLE users DROP CONSTRAINT FK_1483A5E9708A0E0');
        $this->addSql('ALTER TABLE users DROP CONSTRAINT FK_1483A5E9D60322AC');
        $this->addSql('DROP TABLE duree_session');
        $this->addSql('DROP TABLE gender');
        $this->addSql('DROP TABLE generate_pin');
        $this->addSql('DROP TABLE limite_tentative_session');
        $this->addSql('DROP TABLE role');
        $this->addSql('DROP TABLE users');
    }
}
