<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20241219052302 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE duree_session (gender_id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, duree INT NOT NULL, PRIMARY KEY(gender_id))');
        $this->addSql('CREATE TABLE limite_tentative_session (gender_id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, limite INT NOT NULL, PRIMARY KEY(gender_id))');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('DROP TABLE duree_session');
        $this->addSql('DROP TABLE limite_tentative_session');
    }
}
