<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20241218162101 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE generate_pin (generate_pin_id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, date_debut_id TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, date_fin_id TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, pin VARCHAR(100) NOT NULL, user_id INT NOT NULL, PRIMARY KEY(generate_pin_id))');
        $this->addSql('CREATE INDEX IDX_43904F9A76ED395 ON generate_pin (user_id)');
        $this->addSql('ALTER TABLE generate_pin ADD CONSTRAINT FK_43904F9A76ED395 FOREIGN KEY (user_id) REFERENCES users (user_id) NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE generate_pin DROP CONSTRAINT FK_43904F9A76ED395');
        $this->addSql('DROP TABLE generate_pin');
    }
}
